// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// KETERANGAN SIDANG:
/// File ini (firebase_options.dart) TIDAK DIBUAT SECARA MANUAL.
/// File ini di-generate (dibuat otomatis) oleh perintah `flutterfire configure`.
/// Fungsinya adalah menyimpan semua API Key rahasia dan ID Aplikasi Firebase
/// untuk masing-masing platform (Android, iOS, Web, Windows).
/// 
/// Tanpa file ini, aplikasi tidak tahu harus terhubung ke server Firebase yang mana.

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  
  // Fungsi ini otomatis mendeteksi HP user pakai OS apa (Android atau iOS),
  // lalu mengembalikan API Key yang cocok.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android; // Memanggil setingan Android di bawah
      case TargetPlatform.iOS:
        return ios;     // Memanggil setingan iOS di bawah
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // --- KUNCI RAHASIA UNTUK PLATFORM WEB ---
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzUyU9o5yelvBiBvABlS6VlP7dXvFWPz4',
    appId: '1:994050956464:web:9b9e69a15b41763d506f75',
    messagingSenderId: '994050956464',
    projectId: 'daily-development-b320f',
    authDomain: 'daily-development-b320f.firebaseapp.com',
    storageBucket: 'daily-development-b320f.firebasestorage.app',
    measurementId: 'G-CQFKTQ4XF5',
  );

  // --- KUNCI RAHASIA UNTUK PLATFORM ANDROID ---
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwPNhyEvgIV0BFBMqOPIvzEQ9_2w7ndr4',
    appId: '1:994050956464:android:c876f1f3f31017ba506f75',
    messagingSenderId: '994050956464',
    projectId: 'daily-development-b320f',
    storageBucket: 'daily-development-b320f.firebasestorage.app',
  );

  // --- KUNCI RAHASIA UNTUK PLATFORM IOS (IPHONE) ---
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsiQflTQtYHlEbkOA6k8m90vL_zaz4LBA',
    appId: '1:994050956464:ios:fd62003ea4b97c5d506f75',
    messagingSenderId: '994050956464',
    projectId: 'daily-development-b320f',
    storageBucket: 'daily-development-b320f.firebasestorage.app',
    iosBundleId: 'com.example.dailyDevelopment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsiQflTQtYHlEbkOA6k8m90vL_zaz4LBA',
    appId: '1:994050956464:ios:fd62003ea4b97c5d506f75',
    messagingSenderId: '994050956464',
    projectId: 'daily-development-b320f',
    storageBucket: 'daily-development-b320f.firebasestorage.app',
    iosBundleId: 'com.example.dailyDevelopment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzUyU9o5yelvBiBvABlS6VlP7dXvFWPz4',
    appId: '1:994050956464:web:8b11d034d0f859d5506f75',
    messagingSenderId: '994050956464',
    projectId: 'daily-development-b320f',
    authDomain: 'daily-development-b320f.firebaseapp.com',
    storageBucket: 'daily-development-b320f.firebasestorage.app',
    measurementId: 'G-Y92RDRWV6W',
  );
}
